version: '3.4'

services:
  postgres:
    image: postgres:alpine
    container_name: addressmanager
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: addressmanagerdb
    ports:
      - 5432:5432